sudo: required
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem install bundler
  - gem update --remote bundler
install:
  - cd $TRAVIS_BUILD_DIR/discovery_mars; bundle install --retry=3 --without development --without production
script:
  - cd $TRAVIS_BUILD_DIR/discovery_mars; RAILS_ENV=test bundle exec rake db:create db:migrate
  - cd $TRAVIS_BUILD_DIR/discovery_mars; RAILS_ENV=test bundle exec rake
  